version: '3.8'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    command: start-dev
    environment:
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_ADMIN: admin 
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true

      #KC_DB: keycloak
      #KC_HOST: localhost:5431
      #KC_DB_USERNAME: keycloak
      #KC_DB_PASSWORD: keycloak
      #KC_HOSTNAME: localhost
    ports:
      - "8080:8080"
    networks:
      - backend
networks:
  backend:
