version: '3.8'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    command: start-dev
    environment:
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_ADMIN: admin 
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true

      #KC_DB: postgres
      #KC_DB_HOST: keycloak-db
      #KC_DB_USERNAME: keycloak
      #KC_DB_PASSWORD: keycloak
      #KC_DB_PORT: 5432
      
    ports:
      - "8080:8080"
    networks:
      - backend
    volumes:
      - keycloak-data:/opt/keycloak/data
    depends_on:
      - keycloak-db    

  keycloak-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    ports:
      - 5431:5432
    volumes:
      - pgdata:/var/lib/postgresql/data 
    networks:
      - backend

  front:
    restart: always
    ports:
      - "4200:4000"
    build:
      context: ./front
      args:
        env: development

networks:
  backend:

volumes:
  pgdata:
  keycloak-data:
